version: '3.2'

services:
  spreadsheet-crawler-facebook-insight:
    build: ./
    image: marketing-facebook-insight:latest
    volumes:
      - type: bind
        source: /home/thangvm/facebook-credentials
        target: /root/credentials
    environment:
      - DB_URL=jdbc:mysql://sp1.dev.native.vn:3306/marketing_facebook_insight?createDatabaseIfNotExist=true&autoReconnect=true&UseUnicode=true&characterEncoding=utf8&useSSL=false
      - DB_USERNAME=data_warehouse
      - DB_PASSWORD=GUknYz51lOfXk5aqIzuI
      - DB_DDL_AUTO=validate
      - DB_SHOW_SQL=true
      - DB_DIALECT=org.hibernate.dialect.MySQL5InnoDBDialect

      - FB_DRIVEID_POST=1QK2nBQbzPt0jk_kcZMnsAGDbI4wXsgy_
      - FB_DRIVEID_PAGE=1zKD70W6sNXNPdnfwS5oBQbtRnUHbE27J
      - FB_CRAWLER_CRON_POST_DAILY=0 0 23 * * *?
      - FB_CRAWLER_CRON_PAGE_DAILY=0 0 23 * * *?
    networks:
      nvn_net:
networks:
  nvn_net:
